# Generated by Django 3.0.7 on 2020-06-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='place_categories',
            field=models.CharField(choices=[('covid19', 'COVID-19: โรงทานน้ำใจ'), ('rescue', 'Rescue'), ('erhospital', 'ER-Hospital'), ('aed', 'AED'), ('fire', 'Fire: ไฟใหม้'), ('radio', 'Radio: วิทยุ'), ('tree', 'Tree: ต้นไม้'), ('alert', 'Alert: แจ้งเตือน')], max_length=11, verbose_name='Place Categories'),
        ),
    ]
